### ISSUE TITLE
Issues:

### ISSUE THREAD

**Issue by EmmaSweeney** [hlund05/mark-twain_the-innocents-abroad#1]
# General Issues:

- [x] Re-run `se typogrify .` and commit the changes.

- [x] Re-run `se modernize-spelling .` and commit the changes.

- [x] `se find-mismatched-dashes .` shows jack-planed/jackplaned, which can be standardized. Check that sans-peur/sanspeur are acurate to the page scans.

- [x] `se find-mismatched-diacritics .` shows hôte/hote, which can be standardized.

- [x] In the bridgeheads, the clauses need to be sentence-cased.

- [x] There are multiple instances where `<abbr>St.</abbr>` needs to be tagged with `epub:type="z3998:name-title"`. If `St.` is a person's title, it should be tagged.

- [x] You need to add the reference PNG/JPG that you used to make the SVG to the `/images` folder.

- [x] After making the following changes, you shouldn't need a `se-lint-ignore.xml` file anymore.

- [x] **AFTER ALL OTHER CHANGES**, you need to build a dummy repository with the illustrator's name and copy and paste the cover.svg and titlepage.svg files in to your working repository. You will also need re-run `se build-images .`
- [x] **AFTER ALL OTHER CHANGES**, make sure there are no errors when running `se build --check-only .` 

# dedication.xhtml:

- [x] Add `<br/>` elements to match the look of the dedication.

# preface.xhtml:

- [x] The file `<section>` element needs to the `z3998:non-fiction` tag.

- [x] Tag "The Author" as a signature.

# halftitlepage.xhtml:

- [x] Delete `<p>Being Some Account of the Steamship <i epub:type="se:name.vessel.ship">Quaker City</i>’s Pleasure Excursion to Europe and the Holy Land; with Descriptions of Countries, Nations, Incidents and Adventures, as They Appeared to the Author.</p>`. This file should only have the title and subtitle.

# chapter-1.xhtml:

- [x] Remove `epub:type="title"` from the letter header. This semantics is for `<h#>` or in `<hgroup>`  elements

- [x] The letter dateline is missing the `<time datetime="DATE">` tag ([SEMoS 7.7.3.3](https://standardebooks.org/manual/1.8.1/single-page#7.7.3.3)).

- [x] The letter footer needs to be restructured like:
```
				<footer>
					<p epub:type="z3998:signature"><abbr epub:type="z3998:given-name">Chas.</abbr> <abbr epub:type="z3998:given-name">C.</abbr> Duncan,<br/>
					117 Wall Street, New York.</p>
					<p><abbr epub:type="z3998:given-name">R.</abbr> <abbr epub:type="z3998:given-name">R.</abbr> G⁠⸺, Treasurer</p>
					<p>
						<b>Committee on Applications</b>
					</p>
					<p><abbr epub:type="z3998:given-name">J.</abbr> <abbr epub:type="z3998:given-name">T.</abbr> H⁠⸺, <abbr epub:type="z3998:name-title">Esq.</abbr> <abbr epub:type="z3998:given-name">R.</abbr> <abbr epub:type="z3998:given-name">R.</abbr> G⁠⸺, <abbr epub:type="z3998:name-title">Esq.</abbr> <abbr epub:type="z3998:given-name">C.</abbr> <abbr epub:type="z3998:given-name">C.</abbr> Duncan</p>
					<p>
						<b>Committee on Selecting Steamer</b>
					</p>
					<p><abbr epub:type="z3998:name-title">Capt.</abbr> <abbr epub:type="z3998:given-name">W.</abbr> <abbr epub:type="z3998:given-name">W.</abbr> S⁠⸺, <b>Surveyor for Board of Underwriters</b></p>
					<p><abbr epub:type="z3998:given-name">C.</abbr> <abbr epub:type="z3998:given-name">W.</abbr> C⁠⸺, <b>Consulting Engineer for <abbr>U.S.</abbr> and Canada</b></p>
					<p><abbr epub:type="z3998:given-name">J.</abbr> <abbr epub:type="z3998:given-name">T.</abbr> H⁠⸺, <abbr class="eoc" epub:type="z3998:name-title">Esq.</abbr></p>
					<p><abbr epub:type="z3998:given-name">C.</abbr> <abbr epub:type="z3998:given-name">C.</abbr> Duncan</p>
					...
				</footer>
```

- [x] In the letter, replace:
`<p epub:type="z3998:signature"><abbr epub:type="z3998:given-name">Chas.</abbr> <abbr epub:type="z3998:given-name">C.</abbr> Duncan,<br/>`
with
`<p><b epub:type="z3998:sender z3998:signature"><abbr epub:type="z3998:given-name">Chas.</abbr> <abbr epub:type="z3998:given-name">C.</abbr> Duncan</b>,<br/>`

- [x] Tag both instances of `<abbr epub:type="z3998:given-name">C.</abbr> <abbr epub:type="z3998:given-name">C.</abbr> Duncan` as sender and signature.

# chapter-2.xhtml:

- [x] `g⁠— well` contains a partially-obscured word and needs a two-em dash.

# chapter-3.xhtml:

- [x] For `<b>No smoking abaft the wheel</b>`, replace `<b>` with `<strong>`.

# chapter-4.xhtml:

- [x] In `Q. C. Club`, `Q. C.` needs to be tagged as an abbreviation.

# chapter-5.xhtml:

- [x] In the table, the total needs to be in a [`<tfoot>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tfoot).

- [x] For `<b>Total, twenty-one thousand seven hundred reis!</b>`, replace `<b>` with `<strong>`.

# chapter-10.xhtml:

- [x] For `<b>Ladies and Gentlemen</b>`, replace `<b>` with `<strong>`.

# chapter-13.xhtml:

- [x] For `<b>Abdul-Aziz</b>`, replace `<b>` with `<strong>`.

# chapter-19.xhtml:

- [x] `NOTISH.` needs to be title-cased.

# chapter-21.xhtml:

- [x] For `“<b>Venice!</b>”`, replace `<b>` with `<strong>`.

# chapter-26.xhtml:

- [x] The bill needs to be restructured like:
```
			<blockquote>
				<header>
					<p>
						<b>Roman Coliseum</b>
					</p>
					<p>
						<b>Unparalleled Attraction!</b>
					</p>
					<p>
						<b>New Properties! New Lions! New Gladiators!</b>
					</p>
					<p>Engagement of the renowned<br/>
					<b>Marcus Marcellus Valerian!</b><br/>
					<b>For Six Nights Only!</b></p>
				</header>
				<p>The management beg leave to offer to the public an entertainment surpassing in magnificence anything that has heretofore been attempted on any stage. No expense has been spared to make the opening season one which shall be worthy the generous patronage which the management feel sure will crown their efforts. The management beg leave to state that they have succeeded in securing the services of a<br/>
				<b>Galaxy of Talent!</b><br/>
				such as has not been beheld in Rome before.</p>
				<p>The performance will commence this evening with a<br/>
				<b>Grand Broadsword Combat!</b><br/>
				between two young and promising amateurs and a celebrated Parthian gladiator who has just arrived a prisoner from the Camp of Verus.</p>
				<p>This will be followed by a grand moral<br/>
				<b>Battle-Ax Engagement!</b><br/>
				between the renowned Valerian (with one hand tied behind him), and two gigantic savages from Britain.</p>
				<p>After which the renowned Valerian (if he survive), will fight with the broadsword,<br/>
				<b>Left-Handed!</b><br/>
				against six Sophomores and a Freshman from the Gladiatorial College!</p>
				<p>A long series of brilliant engagements will follow, in which the finest talent of the Empire will take part.</p>
				<p>After which the celebrated Infant Prodigy known as<br/>
				<b>“The Young Achilles,”</b><br/>
				will engage four tiger whelps in combat, armed with no other weapon than his little spear!</p>
				<p>The whole to conclude with a chaste and elegant<br/>
				<b>General Slaughter!</b><br/>
				In which thirteen African Lions and twenty-two Barbarian Prisoners will war with each other until all are exterminated.</p>
				<p>
					<b>Box Office Now Open.</b>
				</p>
				<p>Dress Circle One Dollar; Children and Servants half price.</p>
				<p>An efficient police force will be on hand to preserve order and keep the wild beasts from leaping the railings and discommoding the audience.</p>
				<p>Doors open at 7; performance begins at 8.</p>
				<p>
					<span>Positively No Free List.</span>
				</p>
				<footer>
					<p>Diodorus Job Press.</p>
				</footer>
			</blockquote>
```

- [x] In `<b>“The Opening Season.⁠—Coliseum.</b>` the starting `<b>` element needs to be inside the double quotes.

# chapter-29.xhtml:

- [x] This chapter has subsections. Place each section in a `<section>` element. The blockquoted text are the section headers.

# chapter-30.xhtml:

- [x] This chapter has subsections. Place each section in a `<section>` element. The blockquoted text are the section headers.

#chapter-31.xhtml:

- [x] in `Pom-<em>pay</em>-e`, the dashes should be non-breaking hyphens.

- [x] `URIAH` and `GRAUNT⁠` need to be name-cased.

# chapter-51.xhtml:

- [x] The numbered list should be structured as an [ordered list](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol) ([SEMoS 5.6](https://standardebooks.org/manual/1.8.1/single-page#5.6)).

# chapter-59.xhtml:

- [x] The days of the week can be structured as [unordered lists](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul) ([SEMoS 5.6](https://standardebooks.org/manual/1.8.1/single-page#5.6)).

# chapter-61.xhtml:

- [x] You  don't need the `<article>` element. "Return of the Holy Land Excursionists⁠—The Story of the Cruise" goes inside the `<blockquote>`.

- [x] The unsemanticated `<i>` element should be replaced with `<em>`.

# conclusion.xhtml:

- [x] The conclusion should have `afterword` and `backmatter` semantics. The file should be renamed `afterword.xhtml`.

# endnotes.xhtml:

- [x] The author's initials should be in a `<cite>` element.

# local.css:

- [ ] After making the above changes, the custom CSS will need to be updated. If you don't know how to style something, don't worry too much about it. I'll be taking a closer look at the styling in the next review. Getting everything structured correctly is more important.

# content.opf:

- [x] The short description should not have any proper nouns ([SEMoS 9.6.1.2](https://standardebooks.org/manual/1.8.1/9-metadata#9.6.1.2)).

- [x] The book's illustrator was actually True Williams. Fay & Cox made engravings based off of Williams' illustrations for printing.

**Comment by hlund05** [comment]
I've addressed all the issues here, with a few notes / comments:

- In converting the list in chapter 51 to an ordered list, I'm not able to put quotation marks around the numbers.  Is there a way around this (or is it not necessary)?
- Regarding CSS, the one place I struggled was in the chapter 26 playbill.  I'm not sure how to get this looking like the scan (without adding spans and classes as style hooks), so I would appreciate your help with that.    
- I converted the bridgeheads to sentence case.  There are three bridgehead clauses (The Pilgrims Progress, Paradise Lost, Paradise Regained) that I left capitalized as allusions to the famous works.  Does this make sense?  If not I can update them accordingly.  
- Regarding the subtitle of the book itself, I've noticed that it is more often written as "The New Pilgrim's Progress" (singular) rather than "The New Pilgrims' Progress" (plural, as it's currently written).  Should I change this?

**Comment by EmmaSweeney** [comment]
> - In converting the list in chapter 51 to an ordered list, I'm not able to put quotation marks around the numbers. Is there a way around this (or is it not necessary)?

You can have quotes around the list items instead.

> - Regarding CSS, the one place I struggled was in the chapter 26 playbill. I'm not sure how to get this looking like the scan (without adding spans and classes as style hooks), so I would appreciate your help with that.

I'll be taking a thorough look at all the styling in the next review. 

> - I converted the bridgeheads to sentence case. There are three bridgehead clauses (The Pilgrims Progress, Paradise Lost, Paradise Regained) that I left capitalized as allusions to the famous works. Does this make sense? If not I can update them accordingly.

That's fine. Since these are book titles, they need to be tagged with `<i>` and title semantics.

> - Regarding the subtitle of the book itself, I've noticed that it is more often written as "The New Pilgrim's Progress" (singular) rather than "The New Pilgrims' Progress" (plural, as it's currently written). Should I change this?

Yes, this needs to be changed. Make sure both the `content.opf` and `halftitlepage.xhtml` are updated.

I'll review again and help with the CSS once you make the above adjustments .

**Comment by hlund05** [comment]
Thank you -- I've pushed the three updates above.

**Comment by EmmaSweeney** [comment]
# General Issues:

- [x] You still need to copy and paste the `cover.svg` file from a dummy repository with the illustrator's name to the `/images` folder of your working repository.

- [x] You're still missing a reference PNG/JPG that you used to make the illustration. This goes in the `/images` folder.

# dedication.xhtml:

- [x] Instead of adding small-cap styling, use a `<b>` element in the paragraph.

# preface.xhtml:

- [x] I misspoke earlier. You need to apply the `z3998:non-fiction` tag to the `<body>` element, like in the chapter files.

# chapter-1.xhtml:

- [x] In the letter title, remove the period at the end of `Excursion to the Holy Land, Egypt,...`. Titles shouldn't end with periods.

- [x] To make styling easier, add `<div>` elements around the each Committee title and their names.
```
					<div>
						<p>
							<b>Committee on Applications</b>
						</p>
						<p><abbr epub:type="z3998:given-name">J.</abbr> <abbr epub:type="z3998:given-name">T.</abbr> H⁠⸺, <abbr epub:type="z3998:name-title">Esq.</abbr> <abbr epub:type="z3998:given-name">R.</abbr> <abbr epub:type="z3998:given-name">R.</abbr> G⁠⸺, <abbr epub:type="z3998:name-title">Esq.</abbr> <span epub:type="z3998:sender z3998:signature"><abbr epub:type="z3998:given-name">C.</abbr> <abbr epub:type="z3998:given-name">C.</abbr> Duncan</span></p>
					</div>
					<div>
						<p>
							<b>Committee on Selecting Steamer</b>
						</p>
						<p><abbr epub:type="z3998:name-title">Capt.</abbr> <abbr epub:type="z3998:given-name">W.</abbr> <abbr epub:type="z3998:given-name">W.</abbr> S⁠⸺, <b>Surveyor for Board of Underwriters</b></p>
						<p><abbr epub:type="z3998:given-name">C.</abbr> <abbr epub:type="z3998:given-name">W.</abbr> C⁠⸺, <b>Consulting Engineer for <abbr>U.S.</abbr> and Canada</b></p>
						<p><abbr epub:type="z3998:given-name">J.</abbr> <abbr epub:type="z3998:given-name">T.</abbr> H⁠⸺, <abbr class="eoc" epub:type="z3998:name-title">Esq.</abbr></p>
						<p epub:type="z3998:sender z3998:signature"><abbr epub:type="z3998:given-name">C.</abbr> <abbr epub:type="z3998:given-name">C.</abbr> Duncan</p>
					</div>
```

# chapter-13.xhtml:

- [x] In the card, remove the `<header>` element. Use a `<b>` element in the first paragraph instead.

- [x] In the card, add a `<br/>` element after `Guide to Paris, France, Germany,` to match the page scans.

# chapter-19.xhtml:

- [x] In `<p>“<b>Notish.</b>”</p>`, remove the `<b>` element. CSS will take care of it.

- [x] In the image, you're missing `se:image.color-depth.black-on-transparent` semantics ([SEMoS 7.8.4](https://standardebooks.org/manual/1.8.1/single-page#7.8.4)).

# chapter-26.xhtml:

- [x] Since lint complains about `<span>`, switch `<b>` elements to `<strong>` and the `<span>` element to `<b>`.

- [x] For easier styling, place `For Six Nights Only!`in its own paragraph.

# chapter-29.xhtml:

- [x] Remove the `data-parent` attributes in the subchapter `<section>`s. You don't need them if the sections are in the same file as the parent section.

# chapter-30.xhtml:

- [x] Remove the `data-parent` attributes in the subchapter `<section>`s.

# chapter-34.xhtml:

- [x] In `“Sales of one lot Circassians, prime to good, 1852 to 1854, at £240 @ 242, buyer 30;`, you are missing a `½` fraction. See the [page scans](https://archive.org/details/innocentsabroado0000mark_e4a2/page/369/mode/1up).

# chapter-42.xhtml:

- [x] In the verse header, remove the period. Titles shouldn't end with periods.

# chapter-59.xhtml:

- [x] You're missing italics for the days of the week. You can use `<i>` elements.

# endnotes.xhtml:

- [x] In note 9, remove the period at the end of the citation.

# local.css:

- [x] You don't need any custom dedication styling; you just need the CSS in the manual ([SEMoS 7.3.1](https://standardebooks.org/manual/1.8.1/single-page#7.3.1)).

- [x] The letter styling doesn't match the manual. Copy and paste all of the letter CSS ([SEMoS 7.7.4.6.1](https://standardebooks.org/manual/1.8.1/single-page#7.7.4.6.1)). You can delete `[epub|type~="z3998:recipient"]`.

- [x] Remove the custom styling in the `figure` selector. We want to match the manual's styling for images.

- [x] The table CSS can be adjusted:
```
/* Table */
table{
	margin: 1em auto;
}

table td:last-child{
	font-variant-numeric: tabular-nums;
	text-align: right;
}

table tr td:first-child{
	padding-right: 2em;
}

table tfoot tr td:first-child{
	padding-left: 1em;
}

table tfoot tr td:last-child{
	border-top: 1px solid;
}
/* End table */

```
- [x] Delete all other CSS that comes after `abbr[epub|type~="se:era"]{font-variant: all-small-caps;}`. This will all be replaced.

- [x] Add the following custom CSS:
```
/* Standard headers */
header [epub|type~="bridgehead"] + p,
section[epub|type~="z3998:subchapter"] header,
blockquote:not([epub|type~="z3998:letter"]) header p,
#chapter-1 blockquote header p:first-child,
#chapter-42 blockquote[epub|type~="z3998:verse"] header{
	font-variant: small-caps;
	margin: 1em;
	text-align: center;
}
/* End standard headers */

/* Chapter 1 letter */
#chapter-1 blockquote footer div p:first-child{
	margin: 1.5em 1em .5em;
	text-align: center;
	text-indent: 0;
}

#chapter-1 blockquote footer div:first-of-type p:last-child{
	text-align: center;
	text-indent: 0;
}

#chapter-1 blockquote footer p:nth-of-type(2),
#chapter-1 blockquote footer div:last-of-type p + p{
	text-align: initial;
}
/* End chapter 1 letter */

/* Chapter 13 card */
#chapter-13 blockquote{
	border: 1px solid;
	padding: 1.5em 4em;
	text-align: center;
	width: fit-content;
}

#chapter-13 blockquote p + p{
	margin-top: 1em;
	text-indent: 0;
}
/* End chapter 13 card */

/* Chapter 26 bill */
#chapter-26 blockquote:nth-of-type(2) header p{
	margin-bottom: 1em;
	text-indent: 0;
}

#chapter-26 blockquote:nth-of-type(2) strong{
	text-transform: uppercase;
}

#chapter-26 blockquote:nth-of-type(2) header p:first-child{
	font-size: x-large;
	text-decoration: underline;
}

#chapter-26 blockquote:nth-of-type(2) header p:nth-child(2),
#chapter-26 blockquote:nth-of-type(2) header p:nth-child(4) strong{
	font-size: larger;
}

#chapter-26 blockquote:nth-of-type(2) header p:nth-child(4) strong,
#chapter-26 blockquote:nth-of-type(2) > p:nth-of-type(2) strong{
	font-weight: bold;
}

#chapter-26 blockquote:nth-of-type(2) > p strong{
	display: block;
	margin: 1em;
	text-align: center;
	text-indent: 0;
}

#chapter-26 blockquote:nth-of-type(2) > p br{
	display: none;
}

#chapter-26 blockquote:nth-of-type(2) > footer{
	border-top: solid;
	text-align: center;
	text-indent: 0;
}
/* End chapter 26 bill */

/* Chapter 59 notebook */
ul{
	list-style-type: none;
}

ul li + li{
	margin-top: .5em;
}

#chapter-59 ul p{
	text-indent: 1em;
}
/* End chapter 59 notebook */
```

**Comment by hlund05** [comment]
I've addressed all of the new items above except one -- it looks to me like I'm already using the relevant figure CSS from SEMoS (for block-level images).  Could you please let me know what I'm missing for that one?  Thanks.

**Comment by EmmaSweeney** [comment]
Ok, that's fine. I forgot there was a separate figure styling for block-level alignment.

There's a new lint error. Can you address this before I review again?

**Comment by hlund05** [comment]
Apologies - I've addressed that lint error thanks.

**Comment by EmmaSweeney** [comment]
Some minor errors left:

# General Issues:

- [x] Rename `illustration-1-source.png` as `illustration-1.png`.

# chapter-13.xhtml:

- [x] For `<b>Napoleon</b> <span epub:type="z3998:roman">III</span>`, `<b>` needs to be replaced with `<strong>` and surround `Napoleon <span epub:type="z3998:roman">III</span>`.

# chapter-28.xhtml:

- [x] In `<b>To Men of Good Will</b>`, replace `<b>` with `<strong>`. The text should be lower-cased.

- [x] In the Holy Personages rank, replace `<em>` elements used to style "First", "Second", etc. with `<i>`.

# chapter-31.xhtml:

- [x] In `<b>Behold, the World Is Passing Away!</b>`, replace `<b>` with `<strong>`. `Is Passing Away` should be lower-cased.

# chapter-54.xhtml:

- [x] In `“<abbr>S. T.</abbr>⁠—1860⁠—<abbr>X.</abbr>”`, `X.` is not an abbreviation. This inscription was in ads for Drake's Plantation Bitters and is supposed to mean "St. Croix".

# chapter-58.xhtml:

- [x] In `<b>Memory</b>` and `<b>Retrospection</b>`, replace `<b>` with `<strong>`.

# chapter-60.xhtml:

- [x] In `<b>Home</b>`, replace `<b>` with `<strong>`. The text should be lower-cased.

# endnotes.xhtml:

- [x] In note 3, replace `<b>` with `<strong>`.

**Comment by hlund05** [comment]
These edits have all been made thanks
